apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server-app
  template:
    metadata:
      labels:
        component: server-app
    spec:
      containers:
      - name: server
        image: umakantv/multi-server
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: REDIS_PORT
            value: "6379"
          - name: PG_USER
            value: root
          - name: PGHOST
            value: postgres-cluster-ip-service
          - name: PDDATABASE
            value: postgres
          - name: PGPORT
            value: "5432"
