# Each API version defines different set of object configuration we can use 
# v1 defines objects like Pod, Service, Event, Endpoint, Namespace
apiVersion: v1
kind: Service
metadata:
  name: api-node-port
spec:
  type: NodePort
  ports:
  - port: 3050 # to be used by other services in the node
    targetPort: 8080 # container port where the traffic will be routed to
    nodePort: 31515 # port outside the node, to be used from browser
  selector:
    component: api
